### ISSUE TITLE
Save game or level password feature

### ISSUE THREAD

**Issue by paulbowler** [0xC0DE6502/soko-ban-releases#1]
Would love a save game, or level password feature, so I can continue from where I left off from a previous game session rather than having to replay each previous room every time.

**Comment by 0xC0DE6502** [comment]
Hi Paul, on the title screen you can use any of the up/down keys to change the start level. Does that work for you?

**Comment by paulbowler** [comment]
There's nothing on the title screen suggesting use of arrow keys, and the arrow keys don't appear to do anything.

I've tried downloading the latest version for beebem and the online version at bbcmicro.co.uk

Loving all your games - I've even dug out my old Electron with +3 and +1 from the attic which(miraculously) still works perfectly.

**Comment by 0xC0DE6502** [comment]
Thanks Paul, that's awesome to hear and I hope you take good care of your Elk +1 +3 !! I should have been more clear, I meant using the up/down keys, so colon/slash, or K/M.

**Comment by paulbowler** [comment]
Aah, up/down keys do indeed work. Foolish of me not to try them, but arrow keys I suppose seemed more intuitive.

I was 14 when we got our Electron back in 1985 and, although proficient in Basic, never mastered assembler or the specifics of the computer internals or memory map to create games - the resources were simply not readily available in my small town library.

I subsequently studied computer science at university and am now revisiting my past through the burgeoning retro scene. Technical resources on the Internet are now plentiful and complete.

The most complex element of games programming seems to be sprite plotting and movement on the odd character-centric screen memory layout. You've clearly mastered this, and I was wondering if you'd thought about releasing a graphics library as a sideways rom to help others create their own games? It would be a great boost for the community.

Anyway, thanks again for your amazing work,

Paul.

**Comment by 0xC0DE6502** [comment]
My story is actually very, very similar to yours. A few years ago I rediscovered my childhood Electron and have since acquired many more ;) And 6502 asm coding suddenly made sense. I feel like an 80s bedroom coder now haha. I have many projects (and games) on my github. Maybe you will like my e- (electron, get it?) compiler, even though there is no user guide (yet). My "Python" game was written in e- and compiled to 6502 assembly and then assembled with my max65 assembler... such fun! =)

**Comment by paulbowler** [comment]
Will take a look!
